import { CEP_Config } from "vite-cep-plugin";
import { version } from "./package.json";

const config: CEP_Config = {
  version,
  id: "com.bombei.cep",
  displayName: "Bombei",
  symlink: "local",
  port: 3000,
  servePort: 5000,
  startingDebugPort: 8860,
  extensionManifestVersion: 6.0,
  requiredRuntimeVersion: 9.0,
  hosts: [
    { name: "IDSN", version: "[0.0,99.9]" },
    { name: "ILST", version: "[0.0,99.9]" },
    { name: "PHXS", version: "[0.0,99.9]" },
  ],

  type: "Panel",
  iconDarkNormal: "./src/assets/light-icon.png",
  iconNormal: "./src/assets/dark-icon.png",
  iconDarkNormalRollOver: "./src/assets/light-icon.png",
  iconNormalRollOver: "./src/assets/dark-icon.png",
  parameters: ["--v=0", "--enable-nodejs", "--mixed-context"],
  width: 500,
  height: 550,
  panels: [
    {
      mainPath: "./main/index.html",
      name: "main",
      panelDisplayName: "Bombei",
      autoVisible: true,
      width: 55,
      height: 650,
      minWidth: 40,
      minHeight: 370,
      maxWidth: 70,
      maxHeight: 700,
    },
    {
      mainPath: "./main/index.html",
      name: "settings",
      autoVisible: false,
      type: "ModalDialog",
      width: 800,
      height: 650,
      minHeight: 600,
      minWidth: 600,
      maxHeight: 1200,
      maxWidth: 1200,
      startOnEvents: [],
    },
  ],
  build: {
    jsxBin: "off",
    sourceMap: true,
  },
  zxp: {
    country: "US",
    province: "CA",
    org: "MyCompany",
    password: "mypassword",
    tsa: "http://timestamp.digicert.com/",
    sourceMap: false,
    jsxBin: "off",
  },
  installModules: [],
  copyAssets: [],
  copyZipAssets: [],
};
export default config;
